# Generated by Django 5.2.4 on 2025-07-11 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('technical_skills', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('technology_used', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('roles_and_responsibilities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.project')),
            ],
        ),
    ]
